import type { BenyuanQuestion } from "@/lib/benyuan-v3-types";

export const benyuanPart1Questions: BenyuanQuestion[] = [
  {
    id: "A1_core_image",
    module: "A",
    title: "A1. 画面里的自我距离",
    prompt: "翻手机相册时，哪一种画面最容易让你停住，像在替你的自我和世界保持一个距离？",
    kind: "single",
    outputKey: "A1_core_image",
    options: [
      { id: "A1-1", text: "很大的天空、海面、远处的光，自己在里面反而安静下来。", psychologicalSignal: "wide_horizon + meaning_orientation + solitude_capacity + object_distance", tags: ["transcendence", "romanticism", "openness_high", "meaning", "solitude", "object_distance"] },
      { id: "A1-2", text: "山顶、天台、空旷街角，像可以先把和世界的边界放清楚。", psychologicalSignal: "high_place + boundary + solitude_capacity + defense_observe", tags: ["independence", "emotional_restraint", "boundary", "solitude", "observe"] },
      { id: "A1-3", text: "书页、旧房间、桌面小物，像把过去暂时收进一个安全的位置。", psychologicalSignal: "archive_room + repetition + repression + meaning_orientation", tags: ["knowledge_seeking", "nostalgia", "introversion", "repetition", "meaning"] },
      { id: "A1-4", text: "拆掉、重建、换季后的地方，会让我想看看自己还能怎么改变。", psychologicalSignal: "threshold_change + desire_structure + sublimation + repetition", tags: ["change_seeking", "radicalism", "rebirth", "desire", "sublimation"] },
      { id: "A1-5", text: "窗内一盏暖灯、雨声、有人等你回去，但不会急着问太多。", psychologicalSignal: "warm_window + boundary + object_distance + security_need", tags: ["security_need", "warmth_seeking", "boundary", "object_distance"] },
      { id: "A1-6", text: "空舞台、电影院散场后、还没开灯的房间，像有一部分自己还没上场。", psychologicalSignal: "empty_stage + persona + shadow + true_self", tags: ["performativity", "loneliness", "self_observation", "shadow", "真实"] },
      { id: "A1-7", text: "雾、隧道、转弯后的路，看不清，但会想先往前试一小步。", psychologicalSignal: "mist_path + desire_structure + uncertainty_tolerance + defense_observe", tags: ["uncertainty_tolerance", "exploration", "mysticism", "desire", "observe"] },
    ],
  },
  {
    id: "A2_music_analysis",
    module: "A",
    title: "A2. 最近反复听的声音",
    prompt: "上传你最近常听的歌单截图。我们只读取歌曲、氛围和情绪线索，用来让后面的剧场更像从你这里长出来。",
    kind: "upload",
    outputKey: "A2_music_analysis",
    helperText: "上传 1-3 张歌单截图，后续会识别歌曲、艺术家、流派、年代和情绪质地。",
    acceptedFiles: "image/*",
    uploadRange: { min: 1, max: 3 },
    analysisDimensions: ["流派分布", "情绪基调", "年代分布", "语言分布", "艺术家风格"],
  },
  {
    id: "A3_literature",
    module: "A",
    title: "A3. 作品替你说出的部分",
    prompt: "哪些作品曾让你觉得：它不是在讲故事，而是在替你说出某种自我、时间或关系里的难题？（多选，至少选 2 个）",
    kind: "multi",
    minSelections: 2,
    outputKey: "A3_literature",
    options: [
      { id: "A3-1", text: "卡夫卡《变形记》：明明在场，却觉得自己和房间隔着一层壳。", psychologicalSignal: "absurdism + alienation + estranged_self", tags: ["absurdism", "alienation", "existential_anxiety"] },
      { id: "A3-2", text: "加缪《局外人》：那种别人都在要求反应的时候，你却更想先看清事情本身。", psychologicalSignal: "existentialism + distance + lucid_revolt", tags: ["existentialism", "nihilism", "rebellion"] },
      { id: "A3-3", text: "村上春树《挪威的森林》：有些旧时候没有结束，只是变成一段反复回来的音乐。", psychologicalSignal: "youth_memory + loss + private_room", tags: ["loneliness", "youth_nostalgia", "loss"] },
      { id: "A3-4", text: "博尔赫斯《小径分岔的花园》：一个选择之后，仍然会想起那些没有走的时间。", psychologicalSignal: "labyrinth + time_branching + intellectual_mystery", tags: ["labyrinth", "time_philosophy", "intellectualism"] },
      { id: "A3-5", text: "弗吉尼亚·伍尔夫《到灯塔去》：明明一句话还没说出口，心里已经走过很长的潮汐。", psychologicalSignal: "stream_consciousness + interiority + time_wave", tags: ["stream_consciousness", "feminism", "interiority"] },
      { id: "A3-6", text: "马尔克斯《百年孤独》：家族、记忆和命运像绕圈的风，总会把人带回原处。", psychologicalSignal: "magical_realism + family_cycle + fated_return", tags: ["magical_realism", "fatalism", "cyclical_time"] },
      { id: "A3-7", text: "陀思妥耶夫斯基《罪与罚》：有些念头像夜里的审判，越想躲开越会回来。", psychologicalSignal: "moral_pressure + redemption + abyss", tags: ["morality", "redemption", "abyss"] },
      { id: "A3-8", text: "黑塞《悉达多》：比起被安排好的答案，你更想要自己走到河边听见它。", psychologicalSignal: "quest + inner_river + spiritual_search", tags: ["spirituality", "quest", "eastern_philosophy"] },
      { id: "A3-9", text: "卡尔维诺《看不见的城市》：每个地方都像内心地图，藏着一种说不清的秩序。", psychologicalSignal: "imagined_city + poetic_order + construction", tags: ["imagination", "poetic", "construction"] },
      { id: "A3-10", text: "三岛由纪夫《金阁寺》：美突然变得太亮，像让人想靠近又想退后的东西。", psychologicalSignal: "beauty_obsession + sharp_aesthetic + extremity", tags: ["beauty_obsession", "destruction", "extremism"] },
    ],
  },
  {
    id: "A4_cinema",
    module: "A",
    title: "A4. 你愿意住进去的精神天气",
    prompt: "如果一部电影的气质会变成你处理时间、欲望和关系的方式，哪一种更接近？",
    kind: "single",
    outputKey: "A4_cinema",
    options: [
      { id: "A4-1", text: "塔可夫斯基《镜子》：雨、水、记忆和缓慢浮起的时间。", psychologicalSignal: "poetic_time + memory_water + spiritual_cinema", tags: ["poetic", "time_meditation", "spirituality"] },
      { id: "A4-2", text: "大卫·林奇《穆赫兰道》：梦里有门，醒来后还留着谜。", psychologicalSignal: "dream_logic + subconscious_room + surrealism", tags: ["surrealism", "dream_logic", "subconscious"] },
      { id: "A4-3", text: "王家卫《花样年华》：很多话没有说出口，但都留在空气里。", psychologicalSignal: "nostalgia + restraint + unsaid_affection", tags: ["nostalgia", "repression", "eastern_aesthetics"] },
      { id: "A4-4", text: "韦斯·安德森《布达佩斯大饭店》：秩序、颜色和精确摆放的旧梦。", psychologicalSignal: "symmetry + curated_order + playful_control", tags: ["symmetry", "fairy_tale", "order"] },
      { id: "A4-5", text: "泰伦斯·马力克《生命之树》：人的一生被放进更大的风和光里。", psychologicalSignal: "cosmic_nature + philosophical_scale + grace", tags: ["philosophical", "nature", "cosmic"] },
      { id: "A4-6", text: "阿巴斯《樱桃的滋味》：路一直往前，答案藏在很普通的沉默里。", psychologicalSignal: "minimal_road + everyday_existence + quiet_question", tags: ["minimalism", "existential", "mundane"] },
      { id: "A4-7", text: "诺兰《星际穿越》：理性、时间和一件很私人的牵挂纠缠在一起。", psychologicalSignal: "time_complexity + rational_love + cosmic_structure", tags: ["rationality", "time_complexity", "technology"] },
      { id: "A4-8", text: "是枝裕和《小偷家族》：日常很轻，关系却有很深的重量。", psychologicalSignal: "daily_warmth + chosen_family + realism", tags: ["warmth", "family", "realism"] },
    ],
  },
  {
    id: "A5_inspiration_scene",
    module: "A",
    title: "A5. 念头靠近身体的地方",
    prompt: "当你需要把混乱、等待或未说出口的表达放回身体时，哪种场景最容易让念头靠近？",
    kind: "single",
    outputKey: "A5_inspiration_scene",
    options: [
      { id: "A5-1", text: "深夜一个人在桌前，周围终于安静下来。", psychologicalSignal: "night_desk + solitude + knowledge", tags: ["solitude", "knowledge", "night_person"] },
      { id: "A5-2", text: "列车、飞机、出租车上，身体在移动，心也跟着松开。", psychologicalSignal: "transit_space + fluidity + observer", tags: ["liminal_space", "fluidity", "observer"] },
      { id: "A5-3", text: "清晨的公园或山林，空气还没有被一天用旧。", psychologicalSignal: "morning_nature + tranquility + renewal", tags: ["nature", "tranquility", "morning_person"] },
      { id: "A5-4", text: "咖啡馆或街边，周围很热闹，自己反而能听见自己。", psychologicalSignal: "alone_in_crowd + white_noise + social_periphery", tags: ["white_noise", "alone_in_crowd", "social_periphery"] },
      { id: "A5-5", text: "深夜的城市路上，灯还亮着，但没人要求你解释。", psychologicalSignal: "night_city + wandering + urban_observation", tags: ["night_wandering", "marginality", "urban_observation"] },
      { id: "A5-6", text: "洗澡、游泳或靠近水的时候，很多念头会自动浮上来。", psychologicalSignal: "water_body + embodiment + release", tags: ["water_element", "embodiment", "relaxation"] },
      { id: "A5-7", text: "音乐会、展览或剧场里，别人的作品替你打开一扇门。", psychologicalSignal: "art_space + collective_absorption + aesthetic_gate", tags: ["art_immersion", "collective_experience", "aesthetic_absorption"] },
    ],
  },
  {
    id: "B1_night_thoughts",
    module: "B",
    title: "B1. 不确定时的第一反应",
    prompt: "当一件重要的事迟迟没有答案，你更常先进入哪种状态？",
    kind: "single",
    outputKey: "B1_night_thoughts",
    options: [
      { id: "B1-1", text: "我会反复整理已有信息，试图先找到一个可控的判断。", psychologicalSignal: "structured_reasoning + defense_observe + adler_compensation + meaning_orientation", tags: ["rational", "systematic", "observe", "defense", "meaning"] },
      { id: "B1-2", text: "我会暂时放到一边，等自己没那么被它牵动。", psychologicalSignal: "delay + repression + boundary + emotional_regulation", tags: ["avoidant", "repressive", "boundary", "present_oriented"] },
      { id: "B1-3", text: "我会找一个可信的人聊聊，确认自己是不是想多了。", psychologicalSignal: "trusted_mirror + mirror_stage + external_reference + relationship_need", tags: ["relationship_oriented", "external_reference", "mirror", "connection"] },
      { id: "B1-4", text: "我会开始做别的事，用一点行动抵消等待带来的空白。", psychologicalSignal: "movement_first + defense_action + lack + desire_structure", tags: ["action_oriented", "risk_taking", "lack", "desire"] },
      { id: "B1-5", text: "我会先写下来，不急着解决，只让它有个可以停放的位置。", psychologicalSignal: "transitional_space + sublimation + meaning_orientation + containment", tags: ["sublimation", "meaning", "art_space", "真实"] },
      { id: "B1-6", text: "我会一直想这件事背后的意义，像在确认它到底把我带向哪里。", psychologicalSignal: "philosophical_night + meaning_orientation + repetition + self_exploration", tags: ["philosophical", "abstract_thinking", "meaning", "repetition"] },
      { id: "B1-7", text: "我会先让身体休息，能睡就睡，等明天再看它还在不在。", psychologicalSignal: "present_grounding + boundary + defense_delay + low_rumination", tags: ["low_rumination", "present_oriented", "boundary", "defense"] },
    ],
  },
  {
    id: "B2_decision_style",
    module: "B",
    title: "B2. 欲望打乱生活时",
    prompt: "如果你突然很想要某样东西，但它会打乱原本的生活节奏，你通常怎么处理？",
    kind: "single",
    outputKey: "B2_decision_style",
    options: [
      { id: "B2-1", text: "先压一压，看看这种想要会不会自己退去。", psychologicalSignal: "repression + desire_structure + boundary + defense_delay", tags: ["repressive", "boundary", "desire", "avoidant"] },
      { id: "B2-2", text: "认真想它为什么出现，再决定要不要靠近。", psychologicalSignal: "meaning_orientation + desire_structure + observe + self_exploration", tags: ["intuitive", "emotion_guided", "meaning", "observe", "desire"] },
      { id: "B2-3", text: "会找真正可信的人聊聊，看自己有没有漏掉什么。", psychologicalSignal: "trusted_mirror + mirror_stage + external_reference + object_distance", tags: ["relationship_oriented", "external_reference", "mirror", "object_distance"] },
      { id: "B2-4", text: "试着给它一个很小的位置，不让它立刻改变全部。", psychologicalSignal: "transitional_space + desire_structure + boundary + containment", tags: ["boundary", "desire", "art_space", "present_oriented"] },
      { id: "B2-5", text: "如果它足够强烈，我会允许自己先冒一次小险。", psychologicalSignal: "movement_first + desire_structure + risk_taking + true_self", tags: ["action_oriented", "risk_taking", "desire", "真实"] },
      { id: "B2-6", text: "总想等一个更完整的理由出现，不想随便把生活交出去。", psychologicalSignal: "completion_waiting + defense_observe + meaning_orientation + perfectionism", tags: ["perfectionism", "decision_paralysis", "meaning", "defense"] },
    ],
  },
  {
    id: "B3_emotion_pattern",
    module: "B",
    title: "B3. 脆弱出现的方式",
    prompt: "你最不愿意承认自己在哪一刻会变得脆弱？",
    kind: "single",
    outputKey: "B3_emotion_pattern",
    options: [
      { id: "B3-1", text: "当我发现自己其实很在意别人的回应。", psychologicalSignal: "mirror_stage + separation_anxiety + relationship_need + shadow", tags: ["attachment_focus", "mirror", "relationship", "shadow"] },
      { id: "B3-2", text: "我会努力维持平静，但底下已经快要撑不住。", psychologicalSignal: "repression + defense + persona + implicit_emotion", tags: ["repressive", "implicit_emotion", "defense", "persona"] },
      { id: "B3-3", text: "当我明明想靠近，却先表现得好像不需要。", psychologicalSignal: "object_distance + shadow + boundary + desire_structure", tags: ["avoidant_attachment", "boundary", "shadow", "desire"] },
      { id: "B3-4", text: "当我意识到自己并没有想象中那么确定。", psychologicalSignal: "lack + meaning_orientation + defense_observe + uncertainty", tags: ["decision_anxiety", "meaning", "observe", "lack"] },
      { id: "B3-5", text: "当我忍了很久，突然发现一点小事也会让我失控。", psychologicalSignal: "repression + repetition + late_release + shadow", tags: ["accumulative", "explosive", "repressive", "shadow"] },
      { id: "B3-6", text: "我会被很普通的一句话或画面击中，情绪突然变得很满。", psychologicalSignal: "projection + mirror_stage + emotional_resonance + sublimation", tags: ["emotional_resonance", "visual_sensitivity", "mirror", "sublimation"] },
      { id: "B3-7", text: "当我其实需要安慰，却先把自己安排得很正常。", psychologicalSignal: "persona + repression + boundary + true_self", tags: ["positive_baseline", "repressive", "boundary", "真实"] },
    ],
  },
  {
    id: "B4_time_philosophy",
    module: "B",
    title: "B4. 你的时间重力",
    prompt: "如果把注意力分给过去、现在和未来，此刻它们各占多少？",
    kind: "distribution",
    outputKey: "B4_time_philosophy",
    distributionKeys: [
      { key: "past", label: "过去" },
      { key: "present", label: "现在" },
      { key: "future", label: "未来" },
    ],
    helperText: "拖动三个比例，让它们加起来接近你此刻真实的时间感。",
  },
  {
    id: "B5_relationship_philosophy",
    module: "B",
    title: "B5. 关系变远时",
    prompt: "当你感觉一段关系正在变远，你最先注意到的通常是什么？",
    kind: "single",
    outputKey: "B5_relationship_philosophy",
    options: [
      { id: "B5-1", text: "对方回复和语气里的细微变化。", psychologicalSignal: "separation_anxiety + mirror_stage + relationship_need + observe", tags: ["relationship_anxiety", "attachment_focus", "mirror", "observe"] },
      { id: "B5-2", text: "自己开始变得小心，不再像以前那样自然表达。", psychologicalSignal: "boundary + repression + object_distance + true_self", tags: ["deep_connection", "small_circle", "boundary", "repressive"] },
      { id: "B5-3", text: "我会发现两个人之间好像少了一些共同期待。", psychologicalSignal: "meaning_orientation + repetition + object_distance + relationship_need", tags: ["relationship_oriented", "meaning", "repetition", "connection"] },
      { id: "B5-4", text: "我会先判断这是不是还值得继续投入的关系。", psychologicalSignal: "boundary + defense_observe + object_distance + energy_management", tags: ["strong_boundary", "observe", "object_distance", "independent"] },
      { id: "B5-5", text: "靠近可以，但我会先确认对方不会太快进入我全部的房间。", psychologicalSignal: "slow_disclosure + object_distance + engulfment_fear + boundary", tags: ["avoidant_attachment", "strong_boundary", "object_distance", "engulf"] },
      { id: "B5-6", text: "我会换一种表达方式，试试看这段关系还能不能听懂我。", psychologicalSignal: "sublimation + mirror_stage + true_self + relationship_repair", tags: ["adaptive", "mirror", "sublimation", "真实"] },
    ],
  },
  {
    id: "C1_social_posts_analysis",
    module: "C",
    title: "C1. 你曾经公开或半公开留下的话",
    prompt: "上传 1-3 张你喜欢的动态、朋友圈、微博、小红书、备忘录截图。它们会成为剧场里的文字回声。",
    kind: "upload",
    outputKey: "C1_social_posts_analysis",
    helperText: "后续会识别文本情绪、主题、表达风格、自我呈现与时间线索。",
    acceptedFiles: "image/*",
    uploadRange: { min: 1, max: 3 },
    analysisDimensions: ["文本情感", "主题识别", "表达风格", "自我呈现", "时间线索"],
  },
  {
    id: "C2_precious_photo_analysis",
    module: "C",
    title: "C2. 舍不得删除的照片",
    prompt: "上传一张你舍不得删除的照片。它可以很普通，只要它在你这里有重量。",
    kind: "upload",
    outputKey: "C2_precious_photo_analysis",
    helperText: "后续会抽取视觉内容、构图、光线、色彩与象征元素，让它参与剧场和星图。",
    acceptedFiles: "image/*",
    uploadRange: { min: 1, max: 3 },
    analysisDimensions: ["视觉内容", "构图特征", "光线氛围", "色彩情绪", "象征元素"],
  },
  {
    id: "C3_resonance_moments",
    module: "C",
    title: "C3. 未说出口的表达",
    prompt: "哪些时刻，你会觉得某个没有说出口的部分，终于找到了可以表达或被看见的方式？（多选）",
    kind: "multi",
    minSelections: 1,
    outputKey: "C3_resonance_moments",
    options: [
      { id: "C3-1", text: "深夜听到一首歌，突然不想切走，像它替我留住了一点情绪。", psychologicalSignal: "night_music + projection + emotional_resonance + transitional_space + sublimation", tags: ["emotional_resonance", "solitary_comfort", "projection", "sublimation", "music"] },
      { id: "C3-2", text: "读到一句话，像自己没说出口的部分终于被写下来了。", psychologicalSignal: "sentence_mirror + mirror_stage + repression + cognitive_resonance", tags: ["cognitive_resonance", "feeling_understood", "mirror", "repressive"] },
      { id: "C3-3", text: "明明想靠近一个人，却先表现得不需要，后来在作品里认出了自己。", psychologicalSignal: "object_distance + shadow + desire_structure + projection", tags: ["relational_resonance", "connection_need", "object_distance", "shadow", "desire"] },
      { id: "C3-4", text: "看到一个场景或画面，心里某个地方突然亮了一下。", psychologicalSignal: "visual_strike + projection + aesthetic_resonance + sublimation", tags: ["aesthetic_resonance", "visual_sensitivity", "projection", "sublimation"] },
      { id: "C3-5", text: "一个人走路、旅行或坐车时，突然和自己对上了话。", psychologicalSignal: "walking_self_dialogue + meaning_orientation + solitude_capacity + repetition", tags: ["existential_resonance", "self_dialogue", "meaning", "solitude"] },
      { id: "C3-6", text: "写东西、拍照、剪视频、做作品时，终于能把感觉放出来。", psychologicalSignal: "making_as_release + sublimation + true_self + creative_resonance", tags: ["creative_resonance", "self_actualization", "sublimation", "真实"] },
      { id: "C3-7", text: "很少有这种感觉，更多时候像隔着一层玻璃，只能先看着。", psychologicalSignal: "glass_distance + object_distance + defense_observe + alienation", tags: ["resonance_difficulty", "alienation", "object_distance", "observe"] },
    ],
  },
];

export const benyuanQuestionsById = Object.fromEntries(benyuanPart1Questions.map((question) => [question.id, question]));

export const benyuanQuestionsByModule = {
  A: benyuanPart1Questions.filter((question) => question.module === "A"),
  B: benyuanPart1Questions.filter((question) => question.module === "B"),
  C: benyuanPart1Questions.filter((question) => question.module === "C"),
};

export function getQuestionOption(questionId: string, optionId: string) {
  const question = benyuanQuestionsById[questionId];
  return question?.options?.find((option) => option.id === optionId);
}

export function getQuestionOptionTags(questionId: string, optionId: string) {
  return getQuestionOption(questionId, optionId)?.tags ?? [];
}
