import type { BenyuanQuestion } from "@/lib/benyuan-v3-types";

export const benyuanPart1Questions: BenyuanQuestion[] = [
  {
    id: "A1_core_image",
    module: "A",
    title: "A1. 核心意象",
    prompt: "闭上眼睛，想象一个让你感到“这就是我”的画面。它可能是……",
    kind: "single",
    outputKey: "A1_core_image",
    options: [
      { id: "A1-1", text: "🌌 无边际的星空与大海交界", psychologicalSignal: "超越性渴望 + 浪漫主义 + 开放性高", tags: ["transcendence", "romanticism", "openness_high"] },
      { id: "A1-2", text: "🏔️ 孤独的雪山之巅", psychologicalSignal: "独立性 + 精英意识 + 情感克制", tags: ["independence", "elitism", "emotional_restraint"] },
      { id: "A1-3", text: "🌿 被藤蔓包围的古老图书馆", psychologicalSignal: "知识渴望 + 怀旧 + 内向性", tags: ["knowledge_seeking", "nostalgia", "introversion"] },
      { id: "A1-4", text: "🔥 燃烧的森林与新生的绿芽", psychologicalSignal: "毁灭与重生 + 激进性 + 变革渴望", tags: ["destruction_rebirth", "radicalism", "change_seeking"] },
      { id: "A1-5", text: "🏡 温暖灯光的小屋，窗外是雨夜", psychologicalSignal: "安全需求 + 温暖渴望 + 边界感", tags: ["security_need", "warmth_seeking", "boundary"] },
      { id: "A1-6", text: "🎭 空无一人的剧场舞台", psychologicalSignal: "表演性 + 孤独感 + 存在焦虑", tags: ["performativity", "loneliness", "existential_anxiety"] },
      { id: "A1-7", text: "🌫️ 迷雾中若隐若现的小径", psychologicalSignal: "不确定性接纳 + 探索性 + 神秘倾向", tags: ["uncertainty_tolerance", "exploration", "mysticism"] },
    ],
  },
  {
    id: "A2_music_analysis",
    module: "A",
    title: "A2. 音乐偏好",
    prompt: "上传你最近常听的歌单截图（网易云 / QQ 音乐 / Spotify 等）。我们会分析你的音乐品味，但不会保存或分享你的数据。",
    kind: "upload",
    outputKey: "A2_music_analysis",
    helperText: "上传 1-3 张歌单截图，后续多模态分析会自动识别歌曲、艺术家、流派和情绪标签。",
    acceptedFiles: "image/*",
    uploadRange: { min: 1, max: 3 },
    analysisDimensions: ["流派分布", "情绪基调", "年代分布", "语言分布", "艺术家风格"],
  },
  {
    id: "A3_literature",
    module: "A",
    title: "A3. 文学共鸣",
    prompt: "以下哪些作家 / 作品，曾让你产生强烈共鸣？（多选，至少选 2 个）",
    kind: "multi",
    minSelections: 2,
    outputKey: "A3_literature",
    options: [
      { id: "A3-1", text: "卡夫卡《变形记》", psychologicalSignal: "荒诞 + 异化 + 存在焦虑", tags: ["absurdism", "alienation", "existential_anxiety"] },
      { id: "A3-2", text: "加缪《局外人》", psychologicalSignal: "存在主义 + 虚无 + 反抗", tags: ["existentialism", "nihilism", "rebellion"] },
      { id: "A3-3", text: "村上春树《挪威的森林》", psychologicalSignal: "孤独 + 青春 + 失落", tags: ["loneliness", "youth_nostalgia", "loss"] },
      { id: "A3-4", text: "博尔赫斯《小径分岔的花园》", psychologicalSignal: "迷宫 + 时间 + 哲学", tags: ["labyrinth", "time_philosophy", "intellectualism"] },
      { id: "A3-5", text: "弗吉尼亚·伍尔夫《到灯塔去》", psychologicalSignal: "意识流 + 女性 + 内心", tags: ["stream_consciousness", "feminism", "interiority"] },
      { id: "A3-6", text: "马尔克斯《百年孤独》", psychologicalSignal: "魔幻现实 + 宿命 + 循环", tags: ["magical_realism", "fatalism", "cyclical_time"] },
      { id: "A3-7", text: "陀思妥耶夫斯基《罪与罚》", psychologicalSignal: "道德 + 救赎 + 深渊", tags: ["morality", "redemption", "abyss"] },
      { id: "A3-8", text: "黑塞《悉达多》", psychologicalSignal: "灵性 + 追寻 + 东方哲学", tags: ["spirituality", "quest", "eastern_philosophy"] },
      { id: "A3-9", text: "卡尔维诺《看不见的城市》", psychologicalSignal: "想象 + 诗意 + 建构", tags: ["imagination", "poetic", "construction"] },
      { id: "A3-10", text: "三岛由纪夫《金阁寺》", psychologicalSignal: "美 + 毁灭 + 极端", tags: ["beauty_obsession", "destruction", "extremism"] },
    ],
  },
  {
    id: "A4_cinema",
    module: "A",
    title: "A4. 电影美学",
    prompt: "哪位导演的电影，最接近你内心的“美”？（单选）",
    kind: "single",
    outputKey: "A4_cinema",
    options: [
      { id: "A4-1", text: "安德烈·塔可夫斯基《镜子》", psychologicalSignal: "诗意 + 时间 + 灵性", tags: ["poetic", "time_meditation", "spirituality"] },
      { id: "A4-2", text: "大卫·林奇《穆赫兰道》", psychologicalSignal: "超现实 + 梦境 + 潜意识", tags: ["surrealism", "dream_logic", "subconscious"] },
      { id: "A4-3", text: "王家卫《花样年华》", psychologicalSignal: "怀旧 + 压抑 + 东方美学", tags: ["nostalgia", "repression", "eastern_aesthetics"] },
      { id: "A4-4", text: "韦斯·安德森《布达佩斯大饭店》", psychologicalSignal: "对称 + 童话 + 秩序", tags: ["symmetry", "fairy_tale", "order"] },
      { id: "A4-5", text: "特伦斯·马力克《生命之树》", psychologicalSignal: "哲学 + 自然 + 宇宙", tags: ["philosophical", "nature", "cosmic"] },
      { id: "A4-6", text: "阿巴斯《樱桃的滋味》", psychologicalSignal: "极简 + 存在 + 日常", tags: ["minimalism", "existential", "mundane"] },
      { id: "A4-7", text: "克里斯托弗·诺兰《星际穿越》", psychologicalSignal: "理性 + 时间 + 科技", tags: ["rationality", "time_complexity", "technology"] },
      { id: "A4-8", text: "是枝裕和《小偷家族》", psychologicalSignal: "温情 + 家庭 + 现实", tags: ["warmth", "family", "realism"] },
    ],
  },
  {
    id: "A5_inspiration_scene",
    module: "A",
    title: "A5. 灵感场景",
    prompt: "你最容易产生灵感或深刻思考的场景是？（单选）",
    kind: "single",
    outputKey: "A5_inspiration_scene",
    options: [
      { id: "A5-1", text: "深夜的图书馆或书房", psychologicalSignal: "独处 + 知识 + 夜行性", tags: ["solitude", "knowledge", "night_person"] },
      { id: "A5-2", text: "行驶的列车或飞机上", psychologicalSignal: "过渡空间 + 流动性 + 观察者", tags: ["liminal_space", "fluidity", "observer"] },
      { id: "A5-3", text: "清晨的公园或山林", psychologicalSignal: "自然 + 宁静 + 晨型人", tags: ["nature", "tranquility", "morning_person"] },
      { id: "A5-4", text: "喧闹的咖啡馆", psychologicalSignal: "白噪音 + 人群中的孤独 + 社交边缘", tags: ["white_noise", "alone_in_crowd", "social_periphery"] },
      { id: "A5-5", text: "深夜的街道或城市", psychologicalSignal: "夜游 + 边缘 + 观察", tags: ["night_wandering", "marginality", "urban_observation"] },
      { id: "A5-6", text: "洗澡或游泳时", psychologicalSignal: "水 + 身体 + 放松", tags: ["water_element", "embodiment", "relaxation"] },
      { id: "A5-7", text: "音乐会或剧场中", psychologicalSignal: "艺术 + 集体 + 沉浸", tags: ["art_immersion", "collective_experience", "aesthetic_absorption"] },
    ],
  },
  {
    id: "B1_night_thoughts",
    module: "B",
    title: "B1. 深夜思考",
    prompt: "深夜无法入睡时，你的脑海中最常出现的是……（单选）",
    kind: "single",
    outputKey: "B1_night_thoughts",
    options: [
      { id: "B1-1", text: "“我是谁？我为何存在？”", psychologicalSignal: "存在焦虑 + 自我探索", tags: ["existential_anxiety", "self_exploration"] },
      { id: "B1-2", text: "“我做的选择对吗？如果当初……”", psychologicalSignal: "后悔倾向 + 过去导向", tags: ["regret_tendency", "past_oriented"] },
      { id: "B1-3", text: "“明天 / 未来会怎样？”", psychologicalSignal: "焦虑倾向 + 未来导向", tags: ["anxiety_tendency", "future_oriented"] },
      { id: "B1-4", text: "某个具体的人或关系", psychologicalSignal: "关系焦虑 + 依恋模式", tags: ["relationship_anxiety", "attachment_focus"] },
      { id: "B1-5", text: "创意、灵感、想做的事", psychologicalSignal: "创造性 + 行动导向", tags: ["creativity", "action_oriented"] },
      { id: "B1-6", text: "宇宙、时间、生命的意义", psychologicalSignal: "哲学倾向 + 抽象思维", tags: ["philosophical", "abstract_thinking"] },
      { id: "B1-7", text: "很少深夜思考，通常很快入睡", psychologicalSignal: "低神经质 + 当下导向", tags: ["low_neuroticism", "present_oriented"] },
    ],
  },
  {
    id: "B2_decision_style",
    module: "B",
    title: "B2. 决策风格",
    prompt: "面对重要决定时，你更倾向于……（单选）",
    kind: "single",
    outputKey: "B2_decision_style",
    options: [
      { id: "B2-1", text: "列出所有利弊，理性分析", psychologicalSignal: "理性型 + 系统化", tags: ["rational", "systematic"] },
      { id: "B2-2", text: "相信直觉和第一感觉", psychologicalSignal: "直觉型 + 情感导向", tags: ["intuitive", "emotion_guided"] },
      { id: "B2-3", text: "咨询他人意见，寻求共识", psychologicalSignal: "关系导向 + 外部参照", tags: ["relationship_oriented", "external_reference"] },
      { id: "B2-4", text: "拖延到最后一刻，被迫选择", psychologicalSignal: "回避型 + 决策焦虑", tags: ["avoidant", "decision_anxiety"] },
      { id: "B2-5", text: "快速决定，然后全力以赴", psychologicalSignal: "行动型 + 风险偏好", tags: ["action_oriented", "risk_taking"] },
      { id: "B2-6", text: "寻找“完美”选项，很难下决定", psychologicalSignal: "完美主义 + 决策困难", tags: ["perfectionism", "decision_paralysis"] },
    ],
  },
  {
    id: "B3_emotion_pattern",
    module: "B",
    title: "B3. 情绪模式",
    prompt: "用一个意象来形容你的情绪模式……（单选）",
    kind: "single",
    outputKey: "B3_emotion_pattern",
    options: [
      { id: "B3-1", text: "平静的湖面，偶尔涟漪", psychologicalSignal: "情绪稳定 + 低波动", tags: ["emotional_stability", "low_volatility"] },
      { id: "B3-2", text: "深海的暗流，表面平静", psychologicalSignal: "压抑型 + 内隐情绪", tags: ["repressive", "implicit_emotion"] },
      { id: "B3-3", text: "突然的暴风雨，来去匆匆", psychologicalSignal: "高强度 + 短时程", tags: ["high_intensity", "short_duration"] },
      { id: "B3-4", text: "持续的阴雨天", psychologicalSignal: "低落倾向 + 持续性", tags: ["depressive_tendency", "persistent"] },
      { id: "B3-5", text: "火山，长期积累后爆发", psychologicalSignal: "累积型 + 爆发性", tags: ["accumulative", "explosive"] },
      { id: "B3-6", text: "多变的天气，难以预测", psychologicalSignal: "情绪不稳定 + 高波动", tags: ["emotional_instability", "high_volatility"] },
      { id: "B3-7", text: "灿烂的阳光，偶有乌云", psychologicalSignal: "积极基调 + 偶发负面", tags: ["positive_baseline", "occasional_negative"] },
    ],
  },
  {
    id: "B4_time_philosophy",
    module: "B",
    title: "B4. 时间哲学",
    prompt: "如果用百分比分配，你的注意力在……（拖动分配，总和 100%）",
    kind: "distribution",
    outputKey: "B4_time_philosophy",
    distributionKeys: [
      { key: "past", label: "过去" },
      { key: "present", label: "现在" },
      { key: "future", label: "未来" },
    ],
    helperText: "三个滑块总和必须等于 100%。",
  },
  {
    id: "B5_relationship_philosophy",
    module: "B",
    title: "B5. 关系哲学",
    prompt: "你理想的社交状态是……（单选）",
    kind: "single",
    outputKey: "B5_relationship_philosophy",
    options: [
      { id: "B5-1", text: "大部分时间独处，偶尔高质量社交", psychologicalSignal: "独立型 + 选择性社交", tags: ["independent", "selective_social"] },
      { id: "B5-2", text: "有 2-3 个深度连接的人就够了", psychologicalSignal: "深度关系 + 小圈子", tags: ["deep_connection", "small_circle"] },
      { id: "B5-3", text: "喜欢热闹，享受群体活动", psychologicalSignal: "外向型 + 群体导向", tags: ["extroverted", "group_oriented"] },
      { id: "B5-4", text: "需要一个人完全理解我", psychologicalSignal: "融合渴望 + 依恋焦虑", tags: ["fusion_desire", "attachment_anxiety"] },
      { id: "B5-5", text: "保持距离，不想被过度了解", psychologicalSignal: "回避型依恋 + 边界感强", tags: ["avoidant_attachment", "strong_boundary"] },
      { id: "B5-6", text: "在不同圈子扮演不同角色", psychologicalSignal: "多面性 + 适应性", tags: ["multifaceted", "adaptive"] },
    ],
  },
  {
    id: "C1_social_posts_analysis",
    module: "C",
    title: "C1. 社交动态",
    prompt: "上传 1-3 张你最喜欢的社交动态截图（朋友圈、微博、小红书、备忘录等，任何记录你真实想法的内容）。",
    kind: "upload",
    outputKey: "C1_social_posts_analysis",
    helperText: "后续分析会识别文本情感、主题、表达风格、自我呈现与时间线索。",
    acceptedFiles: "image/*",
    uploadRange: { min: 1, max: 3 },
    analysisDimensions: ["文本情感", "主题识别", "表达风格", "自我呈现", "时间线索"],
  },
  {
    id: "C2_precious_photo_analysis",
    module: "C",
    title: "C2. 珍贵照片",
    prompt: "上传一张对你来说最特别的照片（可以是风景、人物、物品，任何承载重要意义的影像）。",
    kind: "upload",
    outputKey: "C2_precious_photo_analysis",
    helperText: "后续分析会抽取视觉内容、构图、光线、色彩与象征元素。",
    acceptedFiles: "image/*",
    uploadRange: { min: 1, max: 1 },
    analysisDimensions: ["视觉内容", "构图特征", "光线氛围", "色彩情绪", "象征元素"],
  },
  {
    id: "C3_resonance_moments",
    module: "C",
    title: "C3. 共鸣时刻",
    prompt: "哪些时刻，你会感到强烈的“被理解”或“找到共鸣”？（多选）",
    kind: "multi",
    minSelections: 1,
    outputKey: "C3_resonance_moments",
    options: [
      { id: "C3-1", text: "深夜独自听歌时", psychologicalSignal: "情感共鸣 + 孤独慰藉", tags: ["emotional_resonance", "solitary_comfort"] },
      { id: "C3-2", text: "读到某句话产生强烈共鸣时", psychologicalSignal: "认知共鸣 + 被理解感", tags: ["cognitive_resonance", "feeling_understood"] },
      { id: "C3-3", text: "与某人深度对话后", psychologicalSignal: "关系共鸣 + 连接需求", tags: ["relational_resonance", "connection_need"] },
      { id: "C3-4", text: "看到某个场景或画面时", psychologicalSignal: "审美共鸣 + 视觉敏感", tags: ["aesthetic_resonance", "visual_sensitivity"] },
      { id: "C3-5", text: "独自旅行或行走时", psychologicalSignal: "存在共鸣 + 自我对话", tags: ["existential_resonance", "self_dialogue"] },
      { id: "C3-6", text: "创作或表达时", psychologicalSignal: "创造共鸣 + 自我实现", tags: ["creative_resonance", "self_actualization"] },
      { id: "C3-7", text: "很少有这种感觉", psychologicalSignal: "共鸣困难 + 疏离感", tags: ["resonance_difficulty", "alienation"] },
    ],
  },
];

export const benyuanQuestionsById = Object.fromEntries(benyuanPart1Questions.map((question) => [question.id, question]));

export const benyuanQuestionsByModule = {
  A: benyuanPart1Questions.filter((question) => question.module === "A"),
  B: benyuanPart1Questions.filter((question) => question.module === "B"),
  C: benyuanPart1Questions.filter((question) => question.module === "C"),
};

export function getQuestionOption(questionId: string, optionId: string) {
  const question = benyuanQuestionsById[questionId];
  return question?.options?.find((option) => option.id === optionId);
}

export function getQuestionOptionTags(questionId: string, optionId: string) {
  return getQuestionOption(questionId, optionId)?.tags ?? [];
}
