import type { BenyuanQuestion } from "@/lib/benyuan-v3-types";

export const benyuanPart1Questions: BenyuanQuestion[] = [
  {
    id: "A1_core_image",
    module: "A",
    title: "A1. 反复留下的画面",
    prompt: "翻手机相册时，哪一种画面你最容易反复留下，不太舍得删？",
    kind: "single",
    outputKey: "A1_core_image",
    options: [
      { id: "A1-1", text: "很大的天空、海面、远处的光，人在里面显得很小。", psychologicalSignal: "wide_horizon + transcendence + self_scale", tags: ["transcendence", "romanticism", "openness_high"] },
      { id: "A1-2", text: "山顶、天台、空旷街角，像只有自己能待一会儿。", psychologicalSignal: "high_place + independence + emotional_restraint", tags: ["independence", "emotional_restraint", "boundary"] },
      { id: "A1-3", text: "书页、旧房间、桌面小物，安静得像能把时间留住。", psychologicalSignal: "archive_room + knowledge_seeking + nostalgia", tags: ["knowledge_seeking", "nostalgia", "introversion"] },
      { id: "A1-4", text: "拆掉、重建、换季后的地方，旧东西正在变成新东西。", psychologicalSignal: "threshold_change + reconstruction + change_seeking", tags: ["change_seeking", "radicalism", "rebirth"] },
      { id: "A1-5", text: "窗内一盏暖灯、雨声、有人等你回去的感觉。", psychologicalSignal: "warm_window + security_need + attachment_safety", tags: ["security_need", "warmth_seeking", "boundary"] },
      { id: "A1-6", text: "空舞台、电影院散场后、还没开灯的房间。", psychologicalSignal: "empty_stage + performativity + liminal_self", tags: ["performativity", "loneliness", "self_observation"] },
      { id: "A1-7", text: "雾、隧道、转弯后的路，看不清但会想继续往前。", psychologicalSignal: "mist_path + uncertainty_tolerance + exploration", tags: ["uncertainty_tolerance", "exploration", "mysticism"] },
    ],
  },
  {
    id: "A2_music_analysis",
    module: "A",
    title: "A2. 最近反复听的声音",
    prompt: "上传你最近常听的歌单截图。我们只读取歌曲、氛围和情绪线索，用来让后面的剧场更像从你这里长出来。",
    kind: "upload",
    outputKey: "A2_music_analysis",
    helperText: "上传 1-3 张歌单截图，后续会识别歌曲、艺术家、流派、年代和情绪质地。",
    acceptedFiles: "image/*",
    uploadRange: { min: 1, max: 3 },
    analysisDimensions: ["流派分布", "情绪基调", "年代分布", "语言分布", "艺术家风格"],
  },
  {
    id: "A3_literature",
    module: "A",
    title: "A3. 被句子击中的方式",
    prompt: "下面哪些作品或作者，曾让你停下来觉得“这句话像是在说我”？（多选，至少选 2 个）",
    kind: "multi",
    minSelections: 2,
    outputKey: "A3_literature",
    options: [
      { id: "A3-1", text: "卡夫卡《变形记》：明明在场，却觉得自己和房间隔着一层壳。", psychologicalSignal: "absurdism + alienation + estranged_self", tags: ["absurdism", "alienation", "existential_anxiety"] },
      { id: "A3-2", text: "加缪《局外人》：那种别人都在要求反应的时候，你却更想先看清事情本身。", psychologicalSignal: "existentialism + distance + lucid_revolt", tags: ["existentialism", "nihilism", "rebellion"] },
      { id: "A3-3", text: "村上春树《挪威的森林》：有些旧时候没有结束，只是变成一段反复回来的音乐。", psychologicalSignal: "youth_memory + loss + private_room", tags: ["loneliness", "youth_nostalgia", "loss"] },
      { id: "A3-4", text: "博尔赫斯《小径分岔的花园》：一个选择之后，仍然会想起那些没有走的时间。", psychologicalSignal: "labyrinth + time_branching + intellectual_mystery", tags: ["labyrinth", "time_philosophy", "intellectualism"] },
      { id: "A3-5", text: "弗吉尼亚·伍尔夫《到灯塔去》：明明一句话还没说出口，心里已经走过很长的潮汐。", psychologicalSignal: "stream_consciousness + interiority + time_wave", tags: ["stream_consciousness", "feminism", "interiority"] },
      { id: "A3-6", text: "马尔克斯《百年孤独》：家族、记忆和命运像绕圈的风，总会把人带回原处。", psychologicalSignal: "magical_realism + family_cycle + fated_return", tags: ["magical_realism", "fatalism", "cyclical_time"] },
      { id: "A3-7", text: "陀思妥耶夫斯基《罪与罚》：有些念头像夜里的审判，越想躲开越会回来。", psychologicalSignal: "moral_pressure + redemption + abyss", tags: ["morality", "redemption", "abyss"] },
      { id: "A3-8", text: "黑塞《悉达多》：比起被安排好的答案，你更想要自己走到河边听见它。", psychologicalSignal: "quest + inner_river + spiritual_search", tags: ["spirituality", "quest", "eastern_philosophy"] },
      { id: "A3-9", text: "卡尔维诺《看不见的城市》：每个地方都像内心地图，藏着一种说不清的秩序。", psychologicalSignal: "imagined_city + poetic_order + construction", tags: ["imagination", "poetic", "construction"] },
      { id: "A3-10", text: "三岛由纪夫《金阁寺》：美突然变得太亮，像让人想靠近又想退后的东西。", psychologicalSignal: "beauty_obsession + sharp_aesthetic + extremity", tags: ["beauty_obsession", "destruction", "extremism"] },
    ],
  },
  {
    id: "A4_cinema",
    module: "A",
    title: "A4. 你愿意住进去的镜头",
    prompt: "如果一部电影的气质会变成你的内心天气，哪一种更接近？",
    kind: "single",
    outputKey: "A4_cinema",
    options: [
      { id: "A4-1", text: "塔可夫斯基《镜子》：雨、水、记忆和缓慢浮起的时间。", psychologicalSignal: "poetic_time + memory_water + spiritual_cinema", tags: ["poetic", "time_meditation", "spirituality"] },
      { id: "A4-2", text: "大卫·林奇《穆赫兰道》：梦里有门，醒来后还留着谜。", psychologicalSignal: "dream_logic + subconscious_room + surrealism", tags: ["surrealism", "dream_logic", "subconscious"] },
      { id: "A4-3", text: "王家卫《花样年华》：很多话没有说出口，但都留在空气里。", psychologicalSignal: "nostalgia + restraint + unsaid_affection", tags: ["nostalgia", "repression", "eastern_aesthetics"] },
      { id: "A4-4", text: "韦斯·安德森《布达佩斯大饭店》：秩序、颜色和精确摆放的旧梦。", psychologicalSignal: "symmetry + curated_order + playful_control", tags: ["symmetry", "fairy_tale", "order"] },
      { id: "A4-5", text: "泰伦斯·马力克《生命之树》：人的一生被放进更大的风和光里。", psychologicalSignal: "cosmic_nature + philosophical_scale + grace", tags: ["philosophical", "nature", "cosmic"] },
      { id: "A4-6", text: "阿巴斯《樱桃的滋味》：路一直往前，答案藏在很普通的沉默里。", psychologicalSignal: "minimal_road + everyday_existence + quiet_question", tags: ["minimalism", "existential", "mundane"] },
      { id: "A4-7", text: "诺兰《星际穿越》：理性、时间和一件很私人的牵挂纠缠在一起。", psychologicalSignal: "time_complexity + rational_love + cosmic_structure", tags: ["rationality", "time_complexity", "technology"] },
      { id: "A4-8", text: "是枝裕和《小偷家族》：日常很轻，关系却有很深的重量。", psychologicalSignal: "daily_warmth + chosen_family + realism", tags: ["warmth", "family", "realism"] },
    ],
  },
  {
    id: "A5_inspiration_scene",
    module: "A",
    title: "A5. 念头最容易出现的地方",
    prompt: "你最容易突然想明白一些事的场景是？",
    kind: "single",
    outputKey: "A5_inspiration_scene",
    options: [
      { id: "A5-1", text: "深夜一个人在桌前，周围终于安静下来。", psychologicalSignal: "night_desk + solitude + knowledge", tags: ["solitude", "knowledge", "night_person"] },
      { id: "A5-2", text: "列车、飞机、出租车上，身体在移动，心也跟着松开。", psychologicalSignal: "transit_space + fluidity + observer", tags: ["liminal_space", "fluidity", "observer"] },
      { id: "A5-3", text: "清晨的公园或山林，空气还没有被一天用旧。", psychologicalSignal: "morning_nature + tranquility + renewal", tags: ["nature", "tranquility", "morning_person"] },
      { id: "A5-4", text: "咖啡馆或街边，周围很热闹，自己反而能听见自己。", psychologicalSignal: "alone_in_crowd + white_noise + social_periphery", tags: ["white_noise", "alone_in_crowd", "social_periphery"] },
      { id: "A5-5", text: "深夜的城市路上，灯还亮着，但没人要求你解释。", psychologicalSignal: "night_city + wandering + urban_observation", tags: ["night_wandering", "marginality", "urban_observation"] },
      { id: "A5-6", text: "洗澡、游泳或靠近水的时候，很多念头会自动浮上来。", psychologicalSignal: "water_body + embodiment + release", tags: ["water_element", "embodiment", "relaxation"] },
      { id: "A5-7", text: "音乐会、展览或剧场里，别人的作品替你打开一扇门。", psychologicalSignal: "art_space + collective_absorption + aesthetic_gate", tags: ["art_immersion", "collective_experience", "aesthetic_absorption"] },
    ],
  },
  {
    id: "B1_night_thoughts",
    module: "B",
    title: "B1. 深夜最常回来的念头",
    prompt: "夜里睡不着时，哪类念头最常自己走回来？",
    kind: "single",
    outputKey: "B1_night_thoughts",
    options: [
      { id: "B1-1", text: "我到底想成为谁，为什么总觉得还没真正抵达自己。", psychologicalSignal: "self_question + existential_anxiety + self_exploration", tags: ["existential_anxiety", "self_exploration"] },
      { id: "B1-2", text: "如果当时换一种选择，现在会不会完全不同。", psychologicalSignal: "counterfactual_past + regret_tendency", tags: ["regret_tendency", "past_oriented"] },
      { id: "B1-3", text: "接下来会怎样，我有没有能力接住未来。", psychologicalSignal: "future_pressure + anxiety_tendency", tags: ["anxiety_tendency", "future_oriented"] },
      { id: "B1-4", text: "某个人、某段关系，或者一句一直没说出口的话。", psychologicalSignal: "relationship_trace + attachment_focus", tags: ["relationship_anxiety", "attachment_focus"] },
      { id: "B1-5", text: "突然冒出的计划、作品、想做但还没开始的事。", psychologicalSignal: "creative_pressure + action_oriented", tags: ["creativity", "action_oriented"] },
      { id: "B1-6", text: "世界为什么会这样，人为什么这样活，时间最后会把我们带到哪里。", psychologicalSignal: "philosophical_night + abstract_thinking + meaning_seeking", tags: ["philosophical", "abstract_thinking"] },
      { id: "B1-7", text: "通常不会想太多，能睡就先睡，明天再处理。", psychologicalSignal: "present_grounding + low_rumination", tags: ["low_rumination", "present_oriented"] },
    ],
  },
  {
    id: "B2_decision_style",
    module: "B",
    title: "B2. 重要选择来临时",
    prompt: "面对一件会改变生活节奏的决定，你通常先相信什么？",
    kind: "single",
    outputKey: "B2_decision_style",
    options: [
      { id: "B2-1", text: "先把利弊、成本和后果写清楚，心才会稳一点。", psychologicalSignal: "structured_reasoning + systematic", tags: ["rational", "systematic"] },
      { id: "B2-2", text: "身体最先知道答案：靠近时放松，抗拒时收紧。", psychologicalSignal: "body_intuition + emotion_guided", tags: ["intuitive", "emotion_guided", "embodiment"] },
      { id: "B2-3", text: "会找真正了解我的人聊聊，看自己有没有漏掉什么。", psychologicalSignal: "trusted_mirror + external_reference", tags: ["relationship_oriented", "external_reference"] },
      { id: "B2-4", text: "会拖到不能再拖，因为太早决定像把可能性关掉。", psychologicalSignal: "delayed_choice + avoidance + ambiguity", tags: ["avoidant", "decision_anxiety"] },
      { id: "B2-5", text: "先做一个方向，路上再调整，停太久反而更难受。", psychologicalSignal: "movement_first + risk_taking", tags: ["action_oriented", "risk_taking"] },
      { id: "B2-6", text: "总想等一个更完整的答案出现，不想随便交卷。", psychologicalSignal: "completion_waiting + perfectionism", tags: ["perfectionism", "decision_paralysis"] },
    ],
  },
  {
    id: "B3_emotion_pattern",
    module: "B",
    title: "B3. 情绪在你身体里的样子",
    prompt: "如果不解释原因，只说它来的方式，更像哪一种？",
    kind: "single",
    outputKey: "B3_emotion_pattern",
    options: [
      { id: "B3-1", text: "大多数时候平稳，偶尔被一件小事轻轻推开。", psychologicalSignal: "stable_surface + low_volatility", tags: ["emotional_stability", "low_volatility"] },
      { id: "B3-2", text: "表面没什么，底下却一直有一股暗流在走。", psychologicalSignal: "under_current + implicit_emotion", tags: ["repressive", "implicit_emotion"] },
      { id: "B3-3", text: "来得很快、很满，过一阵又像雨停了一样。", psychologicalSignal: "storm_wave + high_intensity", tags: ["high_intensity", "short_duration"] },
      { id: "B3-4", text: "像连续阴天，不一定剧烈，但会慢慢改变整个人的亮度。", psychologicalSignal: "long_gray_weather + persistent_low", tags: ["low_mood", "persistent"] },
      { id: "B3-5", text: "会先忍很久，直到某个点突然装不下。", psychologicalSignal: "accumulated_pressure + late_release", tags: ["accumulative", "explosive"] },
      { id: "B3-6", text: "变化很快，连自己也不一定提前知道下一秒是什么天气。", psychologicalSignal: "quick_weather + high_volatility", tags: ["emotional_variability", "high_volatility"] },
      { id: "B3-7", text: "底色偏明亮，只是偶尔会被阴影盖住一会儿。", psychologicalSignal: "bright_baseline + occasional_shadow", tags: ["positive_baseline", "occasional_negative"] },
    ],
  },
  {
    id: "B4_time_philosophy",
    module: "B",
    title: "B4. 你的时间重力",
    prompt: "如果把注意力分给过去、现在和未来，此刻它们各占多少？",
    kind: "distribution",
    outputKey: "B4_time_philosophy",
    distributionKeys: [
      { key: "past", label: "过去" },
      { key: "present", label: "现在" },
      { key: "future", label: "未来" },
    ],
    helperText: "拖动三个比例，让它们加起来接近你此刻真实的时间感。",
  },
  {
    id: "B5_relationship_philosophy",
    module: "B",
    title: "B5. 关系里的距离",
    prompt: "一段关系让你觉得舒服，通常需要什么样的距离？",
    kind: "single",
    outputKey: "B5_relationship_philosophy",
    options: [
      { id: "B5-1", text: "大多数时候自己待着，但偶尔能真正聊到深处。", psychologicalSignal: "selective_depth + independent_connection", tags: ["independent", "selective_social"] },
      { id: "B5-2", text: "不需要很多人，有两三个能长期互相理解的人就够。", psychologicalSignal: "small_circle + deep_connection", tags: ["deep_connection", "small_circle"] },
      { id: "B5-3", text: "喜欢有人气的地方，和群体在一起会更有能量。", psychologicalSignal: "group_energy + extroverted", tags: ["extroverted", "group_oriented"] },
      { id: "B5-4", text: "希望有一个人能越过解释，直接懂我真正想说什么。", psychologicalSignal: "fusion_desire + being_known", tags: ["fusion_desire", "attachment_anxiety"] },
      { id: "B5-5", text: "靠近可以，但不要太快知道我全部的房间。", psychologicalSignal: "slow_disclosure + strong_boundary", tags: ["avoidant_attachment", "strong_boundary"] },
      { id: "B5-6", text: "在不同关系里会露出不同侧面，每一面也都是真的。", psychologicalSignal: "many_faces + adaptive_self", tags: ["multifaceted", "adaptive"] },
    ],
  },
  {
    id: "C1_social_posts_analysis",
    module: "C",
    title: "C1. 你曾经公开或半公开留下的话",
    prompt: "上传 1-3 张你喜欢的动态、朋友圈、微博、小红书、备忘录截图。它们会成为剧场里的文字回声。",
    kind: "upload",
    outputKey: "C1_social_posts_analysis",
    helperText: "后续会识别文本情绪、主题、表达风格、自我呈现与时间线索。",
    acceptedFiles: "image/*",
    uploadRange: { min: 1, max: 3 },
    analysisDimensions: ["文本情感", "主题识别", "表达风格", "自我呈现", "时间线索"],
  },
  {
    id: "C2_precious_photo_analysis",
    module: "C",
    title: "C2. 舍不得删除的照片",
    prompt: "上传一张你舍不得删除的照片。它可以很普通，只要它在你这里有重量。",
    kind: "upload",
    outputKey: "C2_precious_photo_analysis",
    helperText: "后续会抽取视觉内容、构图、光线、色彩与象征元素，让它参与剧场和星图。",
    acceptedFiles: "image/*",
    uploadRange: { min: 1, max: 3 },
    analysisDimensions: ["视觉内容", "构图特征", "光线氛围", "色彩情绪", "象征元素"],
  },
  {
    id: "C3_resonance_moments",
    module: "C",
    title: "C3. 被看见的一瞬间",
    prompt: "哪些时刻，你会忽然觉得“好像有人替我说出来了”？（多选）",
    kind: "multi",
    minSelections: 1,
    outputKey: "C3_resonance_moments",
    options: [
      { id: "C3-1", text: "深夜听到一首歌，突然不想切走。", psychologicalSignal: "night_music + emotional_resonance", tags: ["emotional_resonance", "solitary_comfort"] },
      { id: "C3-2", text: "读到一句话，像自己没说出口的部分被写下来了。", psychologicalSignal: "sentence_mirror + cognitive_resonance", tags: ["cognitive_resonance", "feeling_understood"] },
      { id: "C3-3", text: "和某个人聊完，感觉自己不用再解释那么多。", psychologicalSignal: "conversation_relief + connection_need", tags: ["relational_resonance", "connection_need"] },
      { id: "C3-4", text: "看到一个场景或画面，心里某个地方突然亮了一下。", psychologicalSignal: "visual_strike + aesthetic_resonance", tags: ["aesthetic_resonance", "visual_sensitivity"] },
      { id: "C3-5", text: "一个人走路、旅行或坐车时，突然和自己对上了话。", psychologicalSignal: "walking_self_dialogue + existential_resonance", tags: ["existential_resonance", "self_dialogue"] },
      { id: "C3-6", text: "写东西、拍照、剪视频、做作品时，终于能把感觉放出来。", psychologicalSignal: "making_as_release + creative_resonance", tags: ["creative_resonance", "self_actualization"] },
      { id: "C3-7", text: "很少有这种感觉，更多时候像隔着一层玻璃。", psychologicalSignal: "glass_distance + resonance_difficulty", tags: ["resonance_difficulty", "alienation"] },
    ],
  },
];

export const benyuanQuestionsById = Object.fromEntries(benyuanPart1Questions.map((question) => [question.id, question]));

export const benyuanQuestionsByModule = {
  A: benyuanPart1Questions.filter((question) => question.module === "A"),
  B: benyuanPart1Questions.filter((question) => question.module === "B"),
  C: benyuanPart1Questions.filter((question) => question.module === "C"),
};

export function getQuestionOption(questionId: string, optionId: string) {
  const question = benyuanQuestionsById[questionId];
  return question?.options?.find((option) => option.id === optionId);
}

export function getQuestionOptionTags(questionId: string, optionId: string) {
  return getQuestionOption(questionId, optionId)?.tags ?? [];
}
