import type { QuestionDef } from "./types";

export const deepQuestionContent: QuestionDef[] = [
  {
    questionId: "D001",
    moduleId: "entry_state",
    answerType: "multi",
    prompt: "如果把你此刻的人生阶段看作一片地形，你觉得自己正站在哪几种边缘上？",
    options: ["旧秩序正在松动", "新方向已经发亮但还没成形", "关系结构在悄悄改写", "我在重新学习如何安顿自己", "一切看似平稳，但内里在慢慢位移"],
    minSelections: 2,
    maxSelections: 3,
  },
  {
    questionId: "D002",
    moduleId: "cognitive_topology",
    answerType: "single",
    prompt: "面对一个复杂处境时，你更接近哪种第一反应？",
    options: ["先把所有线索摊开，再寻找结构", "先捕捉气味和直觉，之后再验证", "先和人说一说，在对话里找清晰", "先行动一点，让现实给我反馈", "先退后一步，看自己为什么会被它卷进去"],
  },
  {
    questionId: "D003",
    moduleId: "cognitive_topology",
    answerType: "single",
    prompt: "当两种相互矛盾的解释同时成立时，你通常会：",
    options: ["想尽快选出更合理的那一个", "允许两者并存，继续观察", "先看哪一种更能保护现实关系", "会因此陷入长时间反复推演", "把矛盾本身当成值得研究的入口"],
  },
  {
    questionId: "D004",
    moduleId: "cognitive_topology",
    answerType: "scale",
    prompt: "你能多频繁地察觉到：自己正在如何思考，而不是只注意到结论？",
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: { low: "很少", high: "经常能意识到" },
  },
  {
    questionId: "D005",
    moduleId: "emotional_weather",
    answerType: "single",
    prompt: "当情绪最深的时候，它更像在你身上发生什么？",
    options: ["身体先变重，语言变慢", "脑子突然非常清醒，像被冷光照住", "会想立刻逃开或切断感受", "我反而更想靠近它，弄懂它", "像被潮水推远，与周围暂时失去同步"],
  },
  {
    questionId: "D006",
    moduleId: "desire_topology",
    answerType: "single",
    prompt: "如果你深处最想守住一样东西，它更可能是：",
    options: ["不被误解的真实", "可以慢慢长出来的安全感", "不被消耗掉的自由", "一种明确而内在的价值感", "与更大世界重新连上的意义"],
  },
  {
    questionId: "D007",
    moduleId: "desire_topology",
    answerType: "single",
    prompt: "你最深的不安更像来自哪里？",
    options: ["我会不会终究只是被替代", "我会不会一直活成别人期待的样子", "我会不会在亲密里失去边界", "我会不会错过真正属于自己的路", "我会不会始终无法解释自己的存在"],
  },
  {
    questionId: "D008",
    moduleId: "relational_grammar",
    answerType: "single",
    prompt: "当有人真的靠近你时，你更常见的动作是：",
    options: ["先欢迎，再慢慢后退", "表面自然，内里非常谨慎", "会很珍惜，也会害怕被看穿", "只要确认安全，我会逐渐打开", "我常常比对方更快感到负担"],
  },
  {
    questionId: "D009",
    moduleId: "relational_grammar",
    answerType: "single",
    prompt: "你更希望关系中的自己被如何对待？",
    options: ["被允许复杂，而不被催着解释", "被稳定地回应，而不是偶尔热烈", "被尊重边界，不被过度进入", "被理解我话语背后的沉默部分", "被看作一个始终在变化的人"],
  },
  {
    questionId: "D010",
    moduleId: "aesthetic_fingerprint",
    answerType: "multi",
    prompt: "如果你的内在世界有一组长期意象，它们更可能包括：",
    options: ["镜子", "废墟", "门缝里的光", "海岸线", "长廊", "回声", "密林", "未寄出的信"],
    minSelections: 2,
    maxSelections: 4,
  },
  {
    questionId: "D011",
    moduleId: "aesthetic_fingerprint",
    answerType: "single",
    prompt: "哪一类作品更容易让你觉得自己被理解了？",
    options: ["愿意直面黑暗，但不故作夸张", "看似克制，却留下很深回响", "能把孤独写得很辽阔", "能把混乱组织成某种秩序", "没有给答案，却给了陪伴感"],
  },
  {
    questionId: "D012",
    moduleId: "temporal_philosophy",
    answerType: "single",
    prompt: "你与过去、现在、未来的关系更像哪一句？",
    options: ["过去常常把我拉回去", "我在练习把自己留在此刻", "未来像一束很远但稳定的光", "三者经常同时发声，很难分主次", "我更像站在时间边缘看它们流动"],
  },
  {
    questionId: "D013",
    moduleId: "temporal_philosophy",
    answerType: "scale",
    prompt: "你觉得自己最近的人生叙事有多清楚？",
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: { low: "几乎还没有线索", high: "已经能看见主线" },
  },
  {
    questionId: "D014",
    moduleId: "spiritual_dimension",
    answerType: "single",
    prompt: "当你说“意义”这个词时，你更接近哪种感觉？",
    options: ["它像一种被现实磨薄但仍未熄灭的火", "它来自与人、自然或作品的深层连接", "它更像需要自己一点点建造", "我还没有稳定答案，但会持续追问", "它只在极少数高峰时刻短暂出现"],
  },
  {
    questionId: "D015",
    moduleId: "open_reflection",
    answerType: "text",
    prompt: "请描述一个你最近反复回到的画面、梦境或记忆。它不必完整，只要足够诚实。",
    optional: true,
    presentation: { kind: "long_text", helperText: "你可以写场景、身体感受，或一句反复出现的话。" },
  },
  {
    questionId: "D016",
    moduleId: "open_reflection",
    answerType: "text",
    prompt: "如果把现在的你写成一个精神原型的草稿标题，你会先写下什么？为什么？",
    optional: true,
    presentation: { kind: "long_text", helperText: "不用完整，只需要一个足够像你的标题。" },
  },
];
