import type { QuestionDef } from "./types";

export const fullLiteQuestionSet: QuestionDef[] = [
  {
    questionId: "Q001",
    moduleId: "entry_state",
    answerType: "multi",
    prompt: "最近一段时间，你更常停留在哪几种内在天气里？",
    options: ["薄雾一样的恍惚", "持续低压的疲惫", "潮水起伏般的敏感", "短暂但明亮的希望", "说不清来由的急迫感", "难得的平稳与安静"],
    minSelections: 2,
    maxSelections: 3,
  },
  {
    questionId: "Q002",
    moduleId: "entry_state",
    answerType: "single",
    prompt: "如果把你最近的生活比作一段路，你更像是：",
    options: ["在雾里慢慢辨认方向", "刚从旧路上拐弯，脚下还不稳", "在一条熟路上走得越来越熟练", "快步朝一个很远的地方赶去", "暂时停在路边，想弄清自己为什么出发"],
  },
  {
    questionId: "Q003",
    moduleId: "entry_state",
    answerType: "single",
    prompt: "现在的你更容易被哪类片刻击中？",
    options: ["一句像替我说出心事的话", "一个安静到几乎静止的画面", "一段情绪突然漫上来的旋律", "一个让我想起很久以前的气味或场景", "一个关于未来的微小想象"],
  },
  {
    questionId: "Q004",
    moduleId: "emotional_weather",
    answerType: "single",
    prompt: "当情绪真正来临时，它更像：",
    options: ["骤雨，来得快也退得快", "连绵阴天，久久不散", "潮汐，有规律地反复涨落", "深海暗流，表面平静但里面很重", "晨雾，模糊却柔软"],
  },
  {
    questionId: "Q005",
    moduleId: "emotional_weather",
    answerType: "single",
    prompt: "当别人问你“你怎么了”，你最常见的真实状态是：",
    options: ["我知道自己在难过，只是不想解释", "我知道不对劲，但说不出具体是什么", "我能分清楚很多细微感受，但讲出来太费力", "我通常先说“没事”，等自己消化", "我会希望有人继续问下去"],
  },
  {
    questionId: "Q006",
    moduleId: "emotional_weather",
    answerType: "single",
    prompt: "你更像如何处理强烈情绪？",
    options: ["写下来或转成某种表达", "去散步，让身体先带我走出去", "先关起来，等它自己过去", "找一个可信的人说出来", "沉进去，把它感受完整"],
  },
  {
    questionId: "Q007",
    moduleId: "emotional_weather",
    answerType: "scale",
    prompt: "当情绪波动时，你能分辨它具体是“失落、羞耻、失望、空心、委屈、怀念”等不同形状吗？",
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: { low: "几乎不能", high: "大多数时候可以" },
  },
  {
    questionId: "Q008",
    moduleId: "emotional_weather",
    answerType: "single",
    prompt: "你最容易在哪个时刻感到情绪被放大？",
    options: ["深夜，一切安静下来之后", "事情结束以后回想时", "关系里被忽略或误解时", "看到别人继续往前走时", "忽然被某个作品击中时"],
  },
  {
    questionId: "Q009",
    moduleId: "emotional_weather",
    answerType: "single",
    prompt: "以下哪句话最接近你对脆弱的感受？",
    options: ["脆弱是我不轻易示人的部分", "脆弱是我理解别人的入口", "脆弱会让我失去秩序", "脆弱往往和创作或洞察一起出现", "我还不确定自己是否允许它存在"],
  },
  {
    questionId: "Q010",
    moduleId: "emotional_weather",
    answerType: "single",
    prompt: "当你从情绪里走出来，通常是因为：",
    options: ["我终于把它说清楚了", "时间慢慢冲淡了它", "我把它变成了某种作品或表达", "现实事务把我拉回来了", "有人让我感到自己没有被丢下"],
  },
  {
    questionId: "Q011",
    moduleId: "aesthetic_fingerprint",
    answerType: "single",
    prompt: "哪种阅读体验最容易让你产生‘这好像就是我没说出口的东西’？",
    options: ["荒诞中的孤独与异化", "绵长而潮湿的忧郁", "冷静、疏离、近乎透明的清醒", "缓慢但坚定的灵魂追索", "精致、克制、带一点苍凉的情感"],
  },
  {
    questionId: "Q012",
    moduleId: "aesthetic_fingerprint",
    answerType: "single",
    prompt: "下面哪种音乐场景最接近你现在的精神背景音？",
    options: ["深夜独处的爵士钢琴", "暴雨中的后摇器乐", "清晨宏大的古典乐章", "带一点冰冷荧光感的电子声场", "轻微沙哑、贴近耳边的民谣低语"],
  },
  {
    questionId: "Q013",
    moduleId: "aesthetic_fingerprint",
    answerType: "single",
    prompt: "如果必须在以下视觉空间里待上一下午，你会选：",
    options: ["光线克制、留白很多的房间", "旧物很多、带时间痕迹的空间", "梦境感强、边界不清的场景", "秩序清晰、材质冷冽的建筑内部", "自然疯长、略带荒废感的院落"],
  },
  {
    questionId: "Q014",
    moduleId: "aesthetic_fingerprint",
    answerType: "single",
    prompt: "你更容易被哪种“时间感”打动？",
    options: ["旧时代缓慢褪色的痕迹", "当下极短暂的一次发亮", "未来城市里有点孤独的光", "看不清年代、像神话又像梦的时空", "四季更替中反复回来的熟悉感"],
  },
  {
    questionId: "Q015",
    moduleId: "aesthetic_fingerprint",
    answerType: "multi",
    prompt: "哪些词会让你本能地靠近？",
    options: ["废墟", "雾", "回声", "留白", "微光", "潮汐", "密林", "异乡"],
    minSelections: 2,
    maxSelections: 3,
  },
  {
    questionId: "Q016",
    moduleId: "aesthetic_fingerprint",
    answerType: "single",
    prompt: "如果一件作品不那么“完美”，但带有真切裂痕，你通常会：",
    options: ["更容易被打动", "会先看它是否有结构支撑", "我偏爱完成度更高的东西", "要看它是否保留了真诚", "裂痕本身就是作品的核心"],
  },
  {
    questionId: "Q017",
    moduleId: "aesthetic_fingerprint",
    answerType: "single",
    prompt: "当你喜欢一首歌/一本书时，你最在意的是：",
    options: ["它是否替我说出了情绪", "它是否创造了一种能住进去的氛围", "它是否让我感到更清醒", "它是否把复杂体验处理得很克制", "它是否让我对自己产生新的理解"],
  },
  {
    questionId: "Q018",
    moduleId: "aesthetic_fingerprint",
    answerType: "single",
    prompt: "对于“小众”这件事，你更接近：",
    options: ["我会主动寻找少有人知但很像我的作品", "只要真有共鸣，热门或小众都无所谓", "我喜欢经过时间筛选后留下来的经典", "我常被朋友说审美有点偏门", "我更在意作品和我当下状态是否匹配"],
  },
  {
    questionId: "Q019",
    moduleId: "temporal_philosophy",
    answerType: "single",
    prompt: "你更常把自己放在哪个时间方向上理解？",
    options: ["不断回头看发生过什么", "努力守住此刻，不想被别的拉走", "经常被还没到来的事情牵引", "三个方向都会来，但轻重不同", "我更像在时间外观察自己的生活"],
  },
  {
    questionId: "Q020",
    moduleId: "temporal_philosophy",
    answerType: "single",
    prompt: "当你回忆过去时，它更像：",
    options: ["一部细节很多、经常倒带的电影", "几个发亮或发痛的碎片", "一片已经模糊但有气味的雾", "一条能解释今天的暗线", "我尽量不回头看"],
  },
  {
    questionId: "Q021",
    moduleId: "temporal_philosophy",
    answerType: "scale",
    prompt: "你觉得自己的生命故事目前有多连贯？",
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: { low: "很碎，很难串起来", high: "大致能看见一条线索" },
  },
  {
    questionId: "Q022",
    moduleId: "temporal_philosophy",
    answerType: "single",
    prompt: "面对变化时，你更常见的内在动作是：",
    options: ["先抗拒，等到不得不变", "一边不安，一边还是会往前试", "我会主动制造变化感", "如果变化有意义，我会接受它", "我更想先理解变化在夺走什么"],
  },
  {
    questionId: "Q023",
    moduleId: "open_reflection",
    answerType: "text",
    prompt: "有没有一句话、一首歌、一本书，曾让你觉得‘终于有人替我说出来了’？如果有，请写下它，以及它为什么击中你。",
    optional: true,
  },
  {
    questionId: "Q024",
    moduleId: "open_reflection",
    answerType: "text",
    prompt: "如果给半年前的自己留一句话，你会写什么？",
    optional: true,
  },
];


export const liteQuestionSet = fullLiteQuestionSet;

export const fullDeepQuestionSet: QuestionDef[] = [
  {
    questionId: "D001",
    moduleId: "entry_state",
    answerType: "multi",
    prompt: "如果把你此刻的人生阶段看作一片地形，你觉得自己正站在哪几种边缘上？",
    options: ["旧秩序正在松动", "新方向已经发亮但还没成形", "关系结构在悄悄改写", "我在重新学习如何安顿自己", "一切看似平稳，但内里在慢慢位移"],
    minSelections: 2,
    maxSelections: 3,
  },
  {
    questionId: "D002",
    moduleId: "cognitive_topology",
    answerType: "single",
    prompt: "面对一个复杂处境时，你更接近哪种第一反应？",
    options: ["先把所有线索摊开，再寻找结构", "先捕捉气味和直觉，之后再验证", "先和人说一说，在对话里找清晰", "先行动一点，让现实给我反馈", "先退后一步，看自己为什么会被它卷进去"],
  },
  {
    questionId: "D003",
    moduleId: "cognitive_topology",
    answerType: "single",
    prompt: "当两种相互矛盾的解释同时成立时，你通常会：",
    options: ["想尽快选出更合理的那一个", "允许两者并存，继续观察", "先看哪一种更能保护现实关系", "会因此陷入长时间反复推演", "把矛盾本身当成值得研究的入口"],
  },
  {
    questionId: "D004",
    moduleId: "cognitive_topology",
    answerType: "scale",
    prompt: "你能多频繁地察觉到：自己正在如何思考，而不是只注意到结论？",
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: { low: "很少", high: "经常能意识到" },
  },
  {
    questionId: "D005",
    moduleId: "emotional_weather",
    answerType: "single",
    prompt: "当情绪最深的时候，它更像在你身上发生什么？",
    options: ["身体先变重，语言变慢", "脑子突然非常清醒，像被冷光照住", "会想立刻逃开或切断感受", "我反而更想靠近它，弄懂它", "像被潮水推远，与周围暂时失去同步"],
  },
  {
    questionId: "D006",
    moduleId: "desire_topology",
    answerType: "single",
    prompt: "如果你深处最想守住一样东西，它更可能是：",
    options: ["不被误解的真实", "可以慢慢长出来的安全感", "不被消耗掉的自由", "一种明确而内在的价值感", "与更大世界重新连上的意义"],
  },
  {
    questionId: "D007",
    moduleId: "desire_topology",
    answerType: "single",
    prompt: "你最深的不安更像来自哪里？",
    options: ["我会不会终究只是被替代", "我会不会一直活成别人期待的样子", "我会不会在亲密里失去边界", "我会不会错过真正属于自己的路", "我会不会始终无法解释自己的存在"],
  },
  {
    questionId: "D008",
    moduleId: "relational_grammar",
    answerType: "single",
    prompt: "当有人真的靠近你时，你更常见的动作是：",
    options: ["先欢迎，再慢慢后退", "表面自然，内里非常谨慎", "会很珍惜，也会害怕被看穿", "只要确认安全，我会逐渐打开", "我常常比对方更快感到负担"],
  },
  {
    questionId: "D009",
    moduleId: "relational_grammar",
    answerType: "single",
    prompt: "你更希望关系中的自己被如何对待？",
    options: ["被允许复杂，而不被催着解释", "被稳定地回应，而不是偶尔热烈", "被尊重边界，不被过度进入", "被理解我话语背后的沉默部分", "被看作一个始终在变化的人"],
  },
  {
    questionId: "D010",
    moduleId: "aesthetic_fingerprint",
    answerType: "multi",
    prompt: "如果你的内在世界有一组长期意象，它们更可能包括：",
    options: ["镜子", "废墟", "门缝里的光", "海岸线", "长廊", "回声", "密林", "未寄出的信"],
    minSelections: 2,
    maxSelections: 4,
  },
  {
    questionId: "D011",
    moduleId: "aesthetic_fingerprint",
    answerType: "single",
    prompt: "哪一类作品更容易让你觉得自己被理解了？",
    options: ["愿意直面黑暗，但不故作夸张", "看似克制，却留下很深回响", "能把孤独写得很辽阔", "能把混乱组织成某种秩序", "没有给答案，却给了陪伴感"],
  },
  {
    questionId: "D012",
    moduleId: "temporal_philosophy",
    answerType: "single",
    prompt: "你与过去、现在、未来的关系更像哪一句？",
    options: ["过去常常把我拉回去", "我在练习把自己留在此刻", "未来像一束很远但稳定的光", "三者经常同时发声，很难分主次", "我更像站在时间边缘看它们流动"],
  },
  {
    questionId: "D013",
    moduleId: "temporal_philosophy",
    answerType: "scale",
    prompt: "你觉得自己最近的人生叙事有多清楚？",
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: { low: "几乎还没有线索", high: "已经能看见主线" },
  },
  {
    questionId: "D014",
    moduleId: "spiritual_dimension",
    answerType: "single",
    prompt: "当你说“意义”这个词时，你更接近哪种感觉？",
    options: ["它像一种被现实磨薄但仍未熄灭的火", "它来自与人、自然或作品的深层连接", "它更像需要自己一点点建造", "我还没有稳定答案，但会持续追问", "它只在极少数高峰时刻短暂出现"],
  },
  {
    questionId: "D015",
    moduleId: "open_reflection",
    answerType: "text",
    prompt: "请描述一个你最近反复回到的画面、梦境或记忆。它不必完整，只要足够诚实。",
    optional: true,
    presentation: { kind: "long_text", helperText: "你可以写场景、身体感受，或一句反复出现的话。" },
  },
  {
    questionId: "D016",
    moduleId: "open_reflection",
    answerType: "text",
    prompt: "如果把现在的你写成一个精神原型的草稿标题，你会先写下什么？为什么？",
    optional: true,
    presentation: { kind: "long_text", helperText: "不用完整，只需要一个足够像你的标题。" },
  },
];
export const deepQuestionSet = fullDeepQuestionSet;
