export const benyuanDesignTokens = {
  meta: {
    name: "benyuan-minimal-black-gold",
    version: "2026-03-10-v1",
    usage: "Web source of truth for future iOS shell and UI refactors.",
  },
  color: {
    bgVoid: "#000000",
    bgAbyss: "#0A0A0A",
    bgSurface: "#1A1A1A",
    textPrimary: "#FFFFFF",
    textSecondary: "#999999",
    textTertiary: "#666666",
    accentGold: "#D4AF37",
    accentGoldDim: "rgba(212, 175, 55, 0.3)",
    border: "rgba(255, 255, 255, 0.08)",
    overlay: "rgba(0, 0, 0, 0.9)",
    glow: "rgba(212, 175, 55, 0.2)",
  },
  typography: {
    displayFamily: '"SF Pro Display", "PingFang SC", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif',
    bodyFamily: '"SF Pro Text", "PingFang SC", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif',
    monoFamily: '"SF Mono", "Courier New", monospace',
    weights: {
      light: 300,
      normal: 400,
      medium: 500,
      bold: 600,
    },
    sizes: {
      xs: 12,
      sm: 14,
      base: 16,
      lg: 20,
      xl: 28,
      x2l: 40,
      x3l: 56,
      hero: 72,
    },
    bodyLineHeight: 1.65,
    readingLineHeight: 1.8,
    displayTracking: -0.045,
    eyebrowTracking: 0.38,
  },
  spacing: {
    x1: 4,
    x2: 8,
    x3: 12,
    x4: 16,
    x6: 24,
    x8: 32,
    x12: 48,
    x16: 64,
    x24: 96,
    x32: 128,
  },
  motion: {
    fastMs: 150,
    baseMs: 300,
    slowMs: 500,
    slowerMs: 800,
    longPressMs: 3000,
    questionAutoAdvanceMs: 520,
    uploadAutoAdvanceMs: 680,
    easing: {
      easeIn: "cubic-bezier(0.4, 0, 1, 1)",
      easeOut: "cubic-bezier(0, 0, 0.2, 1)",
      easeInOut: "cubic-bezier(0.4, 0, 0.2, 1)",
      easeSmooth: "cubic-bezier(0.25, 0.1, 0.25, 1)",
    },
  },
  layout: {
    containerSm: 640,
    containerMd: 768,
    containerLg: 1024,
    containerXl: 1280,
    navHeight: 56,
    bottomBarHeight: 80,
    minimumTouchTarget: 44,
  },
  surfaces: {
    cardBorderWidth: 1,
    cardCornerRadius: 0,
    glowBlur: 24,
    progressHeight: 1,
    hairlineOpacity: 0.08,
  },
  ios: {
    preferredShell: "hybrid-webview-first",
    safeAreaBackground: "#000000",
    statusBarStyle: "light-content",
    loadingStrategy: "checkpoint-resume",
    notes: [
      "Keep iPhone interactions one-task-per-screen.",
      "Preserve black-gold palette and restrained motion.",
      "Do not rewrite API contracts during shell phase.",
    ],
  },
} as const;

export type BenyuanDesignTokens = typeof benyuanDesignTokens;
